apiVersion: apps/v1
kind: Deployment
metadata:
  name: too-big
  namespace: lab03
spec:
  replicas: 1
  selector:
    matchLabels:
      app: too-big
  template:
    metadata:
      labels:
        app: too-big
    spec:
      containers:
        - name: app
          image: nginx:1.27-alpine
          resources:
            requests:
              cpu: "32"
              memory: 64Gi
            limits:
              cpu: "32"
              memory: 64Gi
